### ISSUE TITLE
Resource Doesn't Exist Error

### ISSUE THREAD

**Issue by jpdevries** [modxcms/Redirector#2]
When attempting to add a redirect I'm getting a resource doesn't exist error.

Steps to Reproduce:
- Install MODX 2.2.13
- Install Redirector-2.2.0-pl
- Create New Redirect
- set pattern to 'thing'
- set context to 'web'
- choose Home resource in dropdown
- notice target is set to '[[~1]]'
- click Save, notice issue

![](http://j4p.us/image/0s2r3x1J3V0m/Screen%20Shot%202014-03-14%20at%209.20.47%20PM.png)

**Comment by bertoost** [comment]
The problem why it isn't working..
MODX parses [[~id]] always as full URL (in the manager) because the resource doesn't belong to the mgr context. Then MODX goes to grab the resource-context and creates a full URL for the target. I check that URL against a resource URI and that's a relative URL, so they don't match.

**Comment by jpdevries** [comment]
Any ideas how to fix? I haven't been able to add a single redirect since upgrading  because of this —

**Comment by bertoost** [comment]
Already fixed it right? Issue can be closed then..
