### ISSUE TITLE
Revo 2.31 Compatible?

### ISSUE THREAD

**Issue by bmilton** [modxcms/Redirector#32]
I've been using 2.04 since there seem to be some problems with regex rules in 2.05.  Now that we've updated to Revo 2.31, 2.05 is the only option for install.  Uninstalled the redirector and then installed 2.05 in Revo 2.31.  I can't create even a basic rule now without an error message of "An error occurred while trying to save the redirect.".

This extra has always been the best option around for 301 management in modx, something I think is a critical piece of functionality for the user base.  There are no 3rd party paid solutions out there.  I really hope this extra is not abandoned.

**Comment by bmilton** [comment]
More details on the error in 2.05.  I am trying to add a simple page redirect rule for a specific context.  Error follows:

 [2014-08-23 09:43:22](ERROR @ /assets/components/redirector/connector.php) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'modRedirect.triggered' in 'field list'
)

[2014-08-23 09:44:06](ERROR @ /assets/components/redirector/connector.php) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'modRedirect.triggered' in 'field list'
)

[2014-08-23 09:44:06](ERROR @ /assets/components/redirector/connector.php) Error 42S22 executing statement:
INSERT INTO `modx_redirects` (`pattern`, `target`, `context_key`, `triggered`, `active`) VALUES ('test123', 'faq.html', 'SepticSystems', 0, 1)
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'triggered' in 'field list'
)

**Comment by vierkantemeter** [comment]
We have had the same problem in 2.3.3, but got it fixed. This error pops up because when you install a newer version of redirector, it sees that the table `modx_redirects` already exists, and so it doesn't create the table, which is different from older versions of redirector.

What you need to do:
- Uninstall and delete all old redirector installs through package manager
- Delete all files, folders and traces of redirector from `core/components`, `core/packages` and `assets/components`
- Go to phpmyadmin and rename or delete the table `modx_redirects` (Yes, you need to re-enter all redirects)
- Now you can install the new redirector (current version 2.0.5 is working)
- When using redirector 2.0.5: you need to patch `plugin.redirector.php`. See https://github.com/modxcms/Redirector/commit/3d243760bfec6e84022d61e821ab5bd29678d9d3)

**Comment by bertoost** [comment]
Update is coming!
Above patch not needed anymore with 2.0.6
